================================================================================
DEPLOYING RESOLUTION TEST TO REMOTE GPU
================================================================================
Remote host: 192.222.52.203
Remote user: ubuntu

1. Uploading test script...
Traceback (most recent call last):
  File "F:\Art\cosmos-houdini-experiments\scripts\deploy_resolution_test.py", line 135, in <module>
    sys.exit(main())
  File "F:\Art\cosmos-houdini-experiments\scripts\deploy_resolution_test.py", line 40, in main
    sftp.put(str(local_script), remote_script)
AttributeError: '_GeneratorContextManager' object has no attribute 'put'
